--- #YAML:1.0
name:               Object-By
version:            v0.07
abstract:           ~
author:
    - Winfried Trumper <pub+perl@wt.tuxomania.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    parent:  0.01
    perl:    
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
